default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  username: postgres
  password: secret

development:
  <<: *default
  database: <%= @app_const_base.underscore %>_development

test:
  <<: *default
  database: <%= @app_const_base.underscore %>_test

production:
  <<: *default
  database: <%= @app_const_base.underscore %>
